import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Paytone_One } from 'next/font/google';
import { Montserrat } from 'next/font/google';
 
const mont=Montserrat({
  subsets:['latin'],
  variable:'--mont'
})
const paytone=Paytone_One({
  subsets:['latin'],
  weight:['400'],
  variable:'--paytone'
})
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={paytone.variable}>{children}</body>
    </html>
  )
}
